db.session.add(Quiz(quizname="Language Quiz",creator_id=2,style=2))

db.session.add(QuizStyle(style_name="Language quiz style",template_file="HTML-languageQuizFinal.html"))

db.session.add(Question(quiz_id=2,question_number=1))
db.session.add(Question(quiz_id=2,question_number=2))
db.session.add(Question(quiz_id=2,question_number=3))
db.session.add(Question(quiz_id=2,question_number=4))
db.session.add(Question(quiz_id=2,question_number=5))
db.session.add(Question(quiz_id=2,question_number=6))
db.session.add(Question(quiz_id=2,question_number=7))
db.session.add(Question(quiz_id=2,question_number=8))
db.session.add(Question(quiz_id=2,question_number=9))
db.session.add(Question(quiz_id=2,question_number=10))

db.session.add(QuestionContent(question_id=1,text_content="What is the Official Language of Taiwan",img_content="taiwan-languageQuiz.jpg"))
db.session.add(QuestionContent(question_id=2,text_content="What is the Official Language of Australia",img_content="australia-languageQuiz.jpg"))
db.session.add(QuestionContent(question_id=3,text_content="What is the Official Language of Norway",img_content="norway-languageQuiz.jpg"))
db.session.add(QuestionContent(question_id=4,text_content="What is the Official Language of Colombia",img_content="colombia-languageQuiz.jpg"))
db.session.add(QuestionContent(question_id=5,text_content="What is the Official Language of Pakistan",img_content="pakistan-languageQuiz.jpg"))
db.session.add(QuestionContent(question_id=6,text_content="What is the Official Language of Ukraine",img_content="ukraine-languageQuiz.jpg"))
db.session.add(QuestionContent(question_id=7,text_content="What is the Official Language of Malaysia",img_content="malaysia-languageQuiz.jpg"))
db.session.add(QuestionContent(question_id=8,text_content="What is the Official Language of Mexico",img_content="mexico-languageQuiz.jpg"))
db.session.add(QuestionContent(question_id=9,text_content="What is the Official Language of Iran",img_content="iran-languageQuiz.jpg"))
db.session.add(QuestionContent(question_id=10,text_content="What is the Official Language of Indonesia",img_content="indonesia-languageQuiz.jpg"))

db.session.add(QuestionChoice(question_id=1,choice_number=1,choice_content="Taiwanese",choice_correct=False))
db.session.add(QuestionChoice(question_id=1,choice_number=2,choice_content="Japanese",choice_correct=False))
db.session.add(QuestionChoice(question_id=1,choice_number=3,choice_content="Mandarin",choice_correct=True))
db.session.add(QuestionChoice(question_id=1,choice_number=4,choice_content="Cantonese",choice_correct=False))

db.session.add(QuestionChoice(question_id=2,choice_number=1,choice_content="English",choice_correct=True))
db.session.add(QuestionChoice(question_id=2,choice_number=2,choice_content="German",choice_correct=False))
db.session.add(QuestionChoice(question_id=2,choice_number=3,choice_content="Korean",choice_correct=False))
db.session.add(QuestionChoice(question_id=2,choice_number=4,choice_content="Russian",choice_correct=False))

db.session.add(QuestionChoice(question_id=3,choice_number=1,choice_content="German",choice_correct=False))
db.session.add(QuestionChoice(question_id=3,choice_number=2,choice_content="Spanish",choice_correct=False))
db.session.add(QuestionChoice(question_id=3,choice_number=3,choice_content="English",choice_correct=False))
db.session.add(QuestionChoice(question_id=3,choice_number=4,choice_content="Romani",choice_correct=True))

db.session.add(QuestionChoice(question_id=4,choice_number=1,choice_content="Spanish",choice_correct=True))
db.session.add(QuestionChoice(question_id=4,choice_number=2,choice_content="Irish",choice_correct=False))
db.session.add(QuestionChoice(question_id=4,choice_number=3,choice_content="Dutch",choice_correct=False))
db.session.add(QuestionChoice(question_id=4,choice_number=4,choice_content="French",choice_correct=False))

db.session.add(QuestionChoice(question_id=5,choice_number=1,choice_content="Perish",choice_correct=False))
db.session.add(QuestionChoice(question_id=5,choice_number=2,choice_content="Hindi",choice_correct=False))
db.session.add(QuestionChoice(question_id=5,choice_number=3,choice_content="Arabic",choice_correct=False))
db.session.add(QuestionChoice(question_id=5,choice_number=4,choice_content="Urdu",choice_correct=True))

db.session.add(QuestionChoice(question_id=6,choice_number=1,choice_content="Ukrainian",choice_correct=True))
db.session.add(QuestionChoice(question_id=6,choice_number=2,choice_content="Russian",choice_correct=False))
db.session.add(QuestionChoice(question_id=6,choice_number=3,choice_content="Greenlandic",choice_correct=False))
db.session.add(QuestionChoice(question_id=6,choice_number=4,choice_content="Galician",choice_correct=False))

db.session.add(QuestionChoice(question_id=7,choice_number=1,choice_content="Malaysian",choice_correct=False))
db.session.add(QuestionChoice(question_id=7,choice_number=2,choice_content="Malayense",choice_correct=False))
db.session.add(QuestionChoice(question_id=7,choice_number=3,choice_content="Mandarin",choice_correct=False))
db.session.add(QuestionChoice(question_id=7,choice_number=4,choice_content="Malay",choice_correct=True))

db.session.add(QuestionChoice(question_id=8,choice_number=1,choice_content="Spanish",choice_correct=True))
db.session.add(QuestionChoice(question_id=8,choice_number=2,choice_content="Mexian",choice_correct=False))
db.session.add(QuestionChoice(question_id=8,choice_number=3,choice_content="Portuguese",choice_correct=False))
db.session.add(QuestionChoice(question_id=8,choice_number=4,choice_content="Welsh",choice_correct=False))

db.session.add(QuestionChoice(question_id=9,choice_number=1,choice_content="Arabic",choice_correct=False))
db.session.add(QuestionChoice(question_id=9,choice_number=2,choice_content="Hebrew",choice_correct=False))
db.session.add(QuestionChoice(question_id=9,choice_number=3,choice_content="Persian",choice_correct=True))
db.session.add(QuestionChoice(question_id=9,choice_number=4,choice_content="Hindi",choice_correct=False))

db.session.add(QuestionChoice(question_id=10,choice_number=1,choice_content="Malay",choice_correct=False))
db.session.add(QuestionChoice(question_id=10,choice_number=2,choice_content="Indonesia",choice_correct=True))
db.session.add(QuestionChoice(question_id=10,choice_number=3,choice_content="Mandarin",choice_correct=False))
db.session.add(QuestionChoice(question_id=10,choice_number=4,choice_content="Thai",choice_correct=False))
